var searchData=
[
  ['a_20code_20region_0',['Selecting a Code Region',['../user_manual.html#autotoc_md51',1,'']]],
  ['a_20glance_1',['At a Glance',['../index.html#autotoc_md2',1,'']]],
  ['a_20project_2',['Opening a Project',['../user_manual.html#autotoc_md38',1,'']]],
  ['acav_3',['Launching ACAV',['../installation.html#autotoc_md15',1,'']]],
  ['acav_4',['&lt;span class=&quot;tt&quot;&gt;acav&lt;/span&gt;',['../user_manual.html#autotoc_md42',1,'']]],
  ['acav_20docker_20podman_20demo_20image_20user_20guide_5',['ACAV Docker/Podman Demo Image - User Guide',['../demo_image.html',1,'']]],
  ['acavastbuilder_6',['AcavAstBuilder',['../classacav_1_1AcavAstBuilder.html',1,'acav']]],
  ['acavastbuilder_2eh_7',['AcavAstBuilder.h',['../AcavAstBuilder_8h.html',1,'']]],
  ['acavjson_8',['AcavJson',['../AstNode_8h.html#a1993925bf84073a8f29fdd2aee21deea',1,'acav']]],
  ['addchild_9',['addChild',['../classacav_1_1AstViewNode.html#afafc5b8de6133b751987acf33d68e851',1,'acav::AstViewNode']]],
  ['added_10',['Added',['../changelog.html#autotoc_md87',1,'']]],
  ['addnode_11',['addNode',['../classacav_1_1SourceLocationIndex.html#a4fe1036b5fe10756df9b1b31b6ae8974',1,'acav::SourceLocationIndex']]],
  ['and_20cache_20recovery_12',['12. AST Compilation Warning and Cache Recovery',['../user_manual.html#autotoc_md35',1,'']]],
  ['and_20compilers_13',['Supported Languages and Compilers',['../user_manual.html#autotoc_md19',1,'']]],
  ['and_20runtime_14',['Containerized Build and Runtime',['../installation.html#autotoc_md14',1,'']]],
  ['and_20scope_15',['Purpose and Scope',['../index.html#autotoc_md3',1,'']]],
  ['appconfig_16',['AppConfig',['../classacav_1_1AppConfig.html',1,'acav']]],
  ['appconfig_2eh_17',['AppConfig.h',['../AppConfig_8h.html',1,'']]],
  ['application_18',['Running the GUI Application',['../demo_image.html#demo_image_running_gui',1,'']]],
  ['applyfont_19',['applyFont',['../classacav_1_1DeclContextView.html#a58a6c1db0582e68553773fd8c4f8cf10',1,'acav::DeclContextView']]],
  ['applyfontsize_20',['applyFontSize',['../classacav_1_1SourceCodeView.html#addde5c27aba450e8a900c78be3d96b1d',1,'acav::SourceCodeView']]],
  ['assets_21',['GitHub Release Assets',['../demo_image.html#autotoc_md78',1,'']]],
  ['ast_22',['AST',['../user_manual.html#autotoc_md64',1,'AST'],['../user_manual.html#autotoc_md53',1,'Searching the AST']]],
  ['ast_23',['&lt;span class=&quot;tt&quot;&gt;make-ast&lt;/span&gt;',['../user_manual.html#autotoc_md44',1,'']]],
  ['ast_20compilation_20warning_20and_20cache_20recovery_24',['12. AST Compilation Warning and Cache Recovery',['../user_manual.html#autotoc_md35',1,'']]],
  ['ast_20data_25',['Exporting AST Data',['../user_manual.html#autotoc_md55',1,'']]],
  ['ast_20file_20explorer_26',['Tree Views (AST / File Explorer)',['../user_manual.html#autotoc_md62',1,'']]],
  ['ast_20node_20search_27',['6. AST Node Search',['../user_manual.html#autotoc_md29',1,'']]],
  ['ast_20view_28',['Source Code / AST View',['../user_manual.html#autotoc_md60',1,'']]],
  ['ast_20visualization_29',['1. AST Visualization',['../user_manual.html#autotoc_md24',1,'']]],
  ['astcontext_30',['AstContext',['../classacav_1_1AstContext.html',1,'acav']]],
  ['astextractionstats_31',['AstExtractionStats',['../structacav_1_1AstExtractionStats.html',1,'acav']]],
  ['astextractorrunner_32',['AstExtractorRunner',['../classacav_1_1AstExtractorRunner.html',1,'acav::AstExtractorRunner'],['../classacav_1_1AstExtractorRunner.html#ae0520e62789cd2adfa6496a678f59c9e',1,'acav::AstExtractorRunner::AstExtractorRunner(AstContext *context, FileManager &amp;fileManager, QObject *parent=nullptr)'],['../classacav_1_1AstExtractorRunner.html#a7c60ba81e71f8f6ee9ddeed01824770c',1,'acav::AstExtractorRunner::AstExtractorRunner(AstContext *context, FileManager &amp;fileManager, AstLoader loader, QObject *parent=nullptr)']]],
  ['astextractorrunner_2eh_33',['AstExtractorRunner.h',['../AstExtractorRunner_8h.html',1,'']]],
  ['astloader_34',['AstLoader',['../classacav_1_1AstExtractorRunner.html#ab36c99cec6314a77342d33c17c538297',1,'acav::AstExtractorRunner']]],
  ['astmodel_35',['AstModel',['../classacav_1_1AstModel.html',1,'acav']]],
  ['astmodel_2eh_36',['AstModel.h',['../AstModel_8h.html',1,'']]],
  ['astnode_37',['AstNode',['../classacav_1_1AstNode.html',1,'acav']]],
  ['astnode_2eh_38',['AstNode.h',['../AstNode_8h.html',1,'']]],
  ['astready_39',['astReady',['../classacav_1_1MakeAstRunner.html#a72e9889c982c3569d7a508136bc0df34',1,'acav::MakeAstRunner']]],
  ['astviewnode_40',['AstViewNode',['../classacav_1_1AstViewNode.html',1,'acav']]],
  ['at_20a_20glance_41',['At a Glance',['../index.html#autotoc_md2',1,'']]],
  ['available_20options_42',['Available Options',['../user_manual.html#autotoc_md68',1,'']]]
];
