var searchData=
[
  ['s_20included_0',['What&apos;s Included',['../md_DOCKER__IMAGE__README.html#autotoc_md92',1,'']]],
  ['scope_1',['Purpose and Scope',['../index.html#autotoc_md3',1,'']]],
  ['search_2',['Search',['../user_manual.html#autotoc_md28',1,'5. Source Code Search'],['../user_manual.html#autotoc_md29',1,'6. AST Node Search']]],
  ['searching_20source_20code_3',['Searching Source Code',['../user_manual.html#autotoc_md52',1,'']]],
  ['searching_20the_20ast_4',['Searching the AST',['../user_manual.html#autotoc_md53',1,'']]],
  ['selecting_20a_20code_20region_5',['Selecting a Code Region',['../user_manual.html#autotoc_md51',1,'']]],
  ['selection_20in_20source_20code_6',['7. Region Selection in Source Code',['../user_manual.html#autotoc_md30',1,'']]],
  ['set_20the_20variables_7',['Step 0: Set the Variables',['../md_DOCKER__IMAGE__README.html#autotoc_md78',1,'']]],
  ['settings_8',['Settings',['../user_manual.html#autotoc_md67',1,'']]],
  ['shortcuts_9',['Keyboard Shortcuts',['../user_manual.html#autotoc_md58',1,'']]],
  ['source_20code_10',['Source Code',['../user_manual.html#autotoc_md30',1,'7. Region Selection in Source Code'],['../user_manual.html#autotoc_md52',1,'Searching Source Code']]],
  ['source_20code_20ast_20view_11',['Source Code / AST View',['../user_manual.html#autotoc_md60',1,'']]],
  ['source_20code_20search_12',['5. Source Code Search',['../user_manual.html#autotoc_md28',1,'']]],
  ['start_13',['Start',['../index.html#autotoc_md4',1,'Quick Start'],['../md_DOCKER__IMAGE__README.html#autotoc_md75',1,'Quick Start']]],
  ['started_14',['Getting Started',['../user_manual.html#autotoc_md37',1,'']]],
  ['step_200_3a_20set_20the_20variables_15',['Step 0: Set the Variables',['../md_DOCKER__IMAGE__README.html#autotoc_md78',1,'']]],
  ['step_201_3a_20load_20the_20image_16',['Step 1: Load the Image',['../md_DOCKER__IMAGE__README.html#autotoc_md79',1,'']]],
  ['step_202_3a_20verify_17',['Step 2: Verify',['../md_DOCKER__IMAGE__README.html#autotoc_md80',1,'']]],
  ['step_203_3a_20quick_20test_18',['Step 3: Quick Test',['../md_DOCKER__IMAGE__README.html#autotoc_md81',1,'']]],
  ['support_19',['Support',['../user_manual.html#autotoc_md70',1,'Support'],['../md_DOCKER__IMAGE__README.html#autotoc_md100',1,'Support']]],
  ['support_20conditional_20',['11. C++20 Modules Support (Conditional)',['../user_manual.html#autotoc_md34',1,'']]],
  ['supported_20languages_20and_20compilers_21',['Supported Languages and Compilers',['../user_manual.html#autotoc_md19',1,'']]],
  ['switching_22',['Focus Switching',['../user_manual.html#autotoc_md59',1,'']]]
];
