var searchData=
[
  ['s_20included_0',['What&apos;s Included',['../demo_image.html#autotoc_md77',1,'']]],
  ['scope_1',['Purpose and Scope',['../index.html#autotoc_md3',1,'']]],
  ['search_2',['Search',['../user_manual.html#autotoc_md28',1,'5. Source Code Search'],['../user_manual.html#autotoc_md29',1,'6. AST Node Search']]],
  ['searching_20source_20code_3',['Searching Source Code',['../user_manual.html#autotoc_md52',1,'']]],
  ['searching_20the_20ast_4',['Searching the AST',['../user_manual.html#autotoc_md53',1,'']]],
  ['see_5',['What You Should See',['../demo_image.html#autotoc_md75',1,'']]],
  ['selecting_20a_20code_20region_6',['Selecting a Code Region',['../user_manual.html#autotoc_md51',1,'']]],
  ['selection_20in_20source_20code_7',['7. Region Selection in Source Code',['../user_manual.html#autotoc_md30',1,'']]],
  ['settings_8',['Settings',['../user_manual.html#autotoc_md67',1,'']]],
  ['shortcuts_9',['Keyboard Shortcuts',['../user_manual.html#autotoc_md58',1,'']]],
  ['should_20see_10',['What You Should See',['../demo_image.html#autotoc_md75',1,'']]],
  ['source_20code_11',['Source Code',['../user_manual.html#autotoc_md30',1,'7. Region Selection in Source Code'],['../user_manual.html#autotoc_md52',1,'Searching Source Code']]],
  ['source_20code_20ast_20view_12',['Source Code / AST View',['../user_manual.html#autotoc_md60',1,'']]],
  ['source_20code_20search_13',['5. Source Code Search',['../user_manual.html#autotoc_md28',1,'']]],
  ['specified_14',['&quot;Cannot open display&quot; or &quot;No protocol specified&quot;',['../demo_image.html#autotoc_md81',1,'']]],
  ['start_15',['Start',['../index.html#autotoc_md4',1,'Quick Start'],['../demo_image.html#demo_image_quick_start',1,'Quick Start']]],
  ['started_16',['Getting Started',['../user_manual.html#autotoc_md37',1,'']]],
  ['startup_20fails_17',['&quot;XDG_RUNTIME_DIR is invalid&quot; or Wayland startup fails',['../demo_image.html#autotoc_md82',1,'']]],
  ['support_18',['Support',['../user_manual.html#autotoc_md70',1,'Support'],['../demo_image.html#autotoc_md85',1,'Support']]],
  ['support_20conditional_19',['11. C++20 Modules Support (Conditional)',['../user_manual.html#autotoc_md34',1,'']]],
  ['supported_20languages_20and_20compilers_20',['Supported Languages and Compilers',['../user_manual.html#autotoc_md19',1,'']]],
  ['switching_21',['Focus Switching',['../user_manual.html#autotoc_md59',1,'']]]
];
